num = -5
a = 6 
b = 7
age = 14
temperture = 30
uder_note = "admin"


# print("Positive" if num > 0 else "Negative")
# result = "EVEN" if num % 2 == 0 else "OOD"
# max_num = a if a > b else b
# min_num = a if a < b else b
# status = "Adult" if age >= 18 else "Child"
# weather = "Hot" if temperture > 20 else "COLD"
# access_level = "Full Access" if uder_note == "admin" else "Limited Access"

print()
